# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-13 10:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='post',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='gram.Profile'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment_post',
            field=models.CharField(max_length=150),
        ),
    ]
