# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-13 16:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0002_auto_20190313_1357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_avatar',
        ),
    ]
